version: '3.1'

services: 
  db:
    image: ortizflorent/ragnarok-mysql:v1.0.1
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragnarokroot
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok

  phpmyadmin:
    image: ortizflorent/ragnarok-phpmyadmin:v1.0.1
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ragnarokroot
    depends_on:
      - db

  ragnarok:
    image: ortizflorent/ragnarok-server:v1.0.1
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - "6900:6900"
      - "6121:6121"
      - "5121:5121"
      - "8888:8888"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  fluxcp:
    image: ortizflorent/ragnarok-fluxcp:v1.0.1
    links:
      - db
      - ragnarok
    depends_on:
      - db
      - ragnarok
    tty: true
    stdin_open: true
    ports:
      - "8081:80"

  wsproxy:
    image: ortizflorent/ragnarok-wsproxy:v1.0.1
    links:
      - ragnarok
    depends_on:
      - ragnarok
    tty: true
    stdin_open: true
    ports:
      - "5999:5999"

  robrowser:
    image: ortizflorent/ragnarok-robrowser:v1.0.1
    links:
      - wsproxy
    depends_on:
      - wsproxy
    tty: true
    stdin_open: true
    ports:
      - "22000:22000"
volumes:
  db_data: {}