version: '3.1'

services: 
  db:
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok

  phpmyadmin:
    build: ./phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: exemple
    depends_on:
      - db

  ragnarok:
    build: ./server
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - "6900:6900"
      - "6121:6121"
      - "5121:5121" 
      - "8888:8888"
      - "5999:5999"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  db_data: {}