# This workflow will manage the build of our Docker images
name: Auto & Manual - Mido-Wippa - Build docker images for Ragnarock server

# Controls when the action will run. 
on:
  # Allows external webhook trigger
  #repository_dispatch:
    # Variables that have to be call in the curl body to start the github actions, otherwise everything trigger it
    # Ex : curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/florentortiz/mido-wippa/dispatches -d '{"event_type":"mido-wippa_webhook"}'
   # types: [mido-wippa_webhook]
      
  # workflow_dispatch : Workflow runs when manually triggered using the UI or API.
  workflow_dispatch:

  #push:
  #  branches:
  #    - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fluxcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: RagnarokDocker/fluxcp/Dockerfile
          push: true
          tags: ortizflorent/ragnarok-fluxcp:latest

  mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: RagnarokDocker/mysql/Dockerfile
          push: true
          tags: ortizflorent/ragnarok-mysql:latest

  phpmyadmin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: RagnarokDocker/phpmyadmin/Dockerfile
          push: true
          tags: ortizflorent/ragnarok-phpmyadmin:latest

  robrowser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: RagnarokDocker/robrowser/Dockerfile
          push: true
          tags: ortizflorent/ragnarok-robrowser:latest

  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: RagnarokDocker/server/Dockerfile
          push: true
          tags: ortizflorent/ragnarok-server:latest

  wsproxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: RagnarokDocker/wsproxy/Dockerfile
          push: true
          tags: ortizflorent/ragnarok-wsproxy:latest